// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwo2i39loOVCnXx5oz-fNmOQHS2byXUp8',
    appId: '1:154474754353:web:34769b0df11c13d3fc0010',
    messagingSenderId: '154474754353',
    projectId: 'flutter-news-app-93dc4',
    authDomain: 'flutter-news-app-93dc4.firebaseapp.com',
    storageBucket: 'flutter-news-app-93dc4.appspot.com',
    measurementId: 'G-8R7W441WM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABQ9osgASSWtfvodzjBwodBTpQjuAJGVA',
    appId: '1:154474754353:android:c5eb376385169524fc0010',
    messagingSenderId: '154474754353',
    projectId: 'flutter-news-app-93dc4',
    storageBucket: 'flutter-news-app-93dc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVySnix5xk1SSZJTMlX0SNct-ByiVVh2M',
    appId: '1:154474754353:ios:557d4ba013cc7b6cfc0010',
    messagingSenderId: '154474754353',
    projectId: 'flutter-news-app-93dc4',
    storageBucket: 'flutter-news-app-93dc4.appspot.com',
    iosClientId: '154474754353-psmb15qq42unmbij8k1j7qjibcqif8ig.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVySnix5xk1SSZJTMlX0SNct-ByiVVh2M',
    appId: '1:154474754353:ios:557d4ba013cc7b6cfc0010',
    messagingSenderId: '154474754353',
    projectId: 'flutter-news-app-93dc4',
    storageBucket: 'flutter-news-app-93dc4.appspot.com',
    iosClientId: '154474754353-psmb15qq42unmbij8k1j7qjibcqif8ig.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsapp',
  );
}
// Future<void> handleBackgroundMessage(RemoteMessage message) async {
//   print("Title : ${message.notification?.title}");
//   print("Body : ${message.notification?.body}");
//   print("payload : ${message.data}");
// }

// class firebaseApi {
//   final _firebaseMessaging = FirebaseMessaging.instance;
//   Future<void> initNotifivation() async {
//     await _firebaseMessaging.requestPermission();
//     final fcmtoken = await _firebaseMessaging.getToken();
//     FirebaseMessaging.onBackgroundMessage(handleBackgroundMessage);
//     print("token: ${fcmtoken}");
//   }
// }
